# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [ "size=4G" "mode=755" ];
  };
  #  { device = "/dev/disk/by-uuid/78bf187d-8a45-4960-8e07-0b9f6dc7cc86";
  #    fsType = "ext4";
  #  };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/da13c119-cf32-401c-a6cd-c39962c14b85";
      fsType = "ext4";
    };

  fileSystems."/home/shared" = {
    device = "/dev/disk/by-label/shared";
    fsType = "ntfs";
  };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/0f408d33-3982-46d9-8451-bafddecd707d";
      fsType = "xfs";
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/73142b64-bd75-42df-87ea-bea67627c90a";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c923cb0c-b681-4ddb-9dbb-adbc2c496a2a"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp230s0f1u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp229s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
